name: Build

on: 
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    env:
      SOURCE_DIR: firmware
      PICO_SDK_FETCH_FROM_GIT: on   # ⭐关键

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y cmake ninja-build gcc-arm-none-eabi libnewlib-arm-none-eabi libstdc++-arm-none-eabi-dev

      - name: Configure build
        run: |
          cmake -G Ninja -S $SOURCE_DIR -B build -DCMAKE_BUILD_TYPE=Release

      - name: Build
        run: |
          cmake --build build

      - name: Upload firmware
        uses: actions/upload-artifact@v4
        with:
          name: firmware.uf2
          path: build/**/*.uf2
